### ISSUE TITLE
show help in debugging connection problems

### ISSUE THREAD

**Issue by thammi** [palavatv/palava#13] opened 2014-11-23 20:00 UTC
<a href="https://github.com/payload"><img src="https://avatars.githubusercontent.com/u/144412?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [payload](https://github.com/payload)**
_Sunday Jan 05, 2014 at 22:28 GMT_
_Originally opened as https://github.com/palavatv/palava-portal/issues/4_

---

When somebody notices connection problems, it is sometimes not obvious why there are problems.
- hole punching didn't do its job (why?)
- slow connection
- is there another possible and detectable issue?

I propose, the cause of such problems should be detected and a user should get the opportunity to see these causes and maybe a helping link how to fix it.

This involves adding detection of errors in the palava-machine, passing information to the clients (palava-client) and integrating a possibility to see this information in the UI (palava-portal). Maybe it also involves adding a little test setup for palava-machine to generate such errors.

What do you think about it?

**Comment by farao** [comment] 2019-03-17 13:12
Duplicate of https://github.com/palavatv/palava/issues/2

**Closed by farao** 2019-03-17 13:12 UTC
